import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "@/styles/tailwindimport.css";
import LayoutBackground from "@/utility/LayoutBackground";

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Reform India",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${geistMono.className} h-full antialiased`}>
            <body className="min-h-full flex flex-col bg-black text-white">
                <LayoutBackground />
                {children}
            </body>
        </html>
    );
}
